// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HotelManagment_Day11.Models
{
    public partial class FRONTEND_RESERVATIONContext : DbContext
    {
        public FRONTEND_RESERVATIONContext()
        {
        }

        public FRONTEND_RESERVATIONContext(DbContextOptions<FRONTEND_RESERVATIONContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring( DbContextOptionsBuilder optionsBuilder )
        {
            if ( !optionsBuilder.IsConfigured )
            {

                optionsBuilder.UseSqlServer( ConfigurationManager.ConnectionStrings[ "DefaultConnection" ].ConnectionString );
            }
        }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}