// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment_Day11.Models
{
    public partial class User
    {
        [Key]
        [Column("username")]
        [StringLength(50)]
        public string Username { get; set; }
        [Column("passward")]
        [StringLength(50)]
        public string Passward { get; set; }
        [Column("role")]
        [StringLength(50)]
        public string Role { get; set; }
    }
}