// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkDay1.Models;

public partial class Publisher
{
    public string PubId { get; set; }

    public string PubName { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public virtual ICollection<Employee> Employees { get; } = new List<Employee>();

    public virtual PubInfo PubInfo { get; set; }

    public virtual ICollection<Title> Titles { get; } = new List<Title>();
}