//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Day04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Stud_Course = new HashSet<Stud_Course>();
            this.Student1 = new HashSet<Student>();
        }
    
        public int St_Id { get; set; }
        public string St_Fname { get; set; }
        public string St_Lname { get; set; }
        public string St_Address { get; set; }
        public Nullable<int> St_Age { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public Nullable<int> St_super { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Stud_Course> Stud_Course { get; set; }
        public virtual ICollection<Student> Student1 { get; set; }
        public virtual Student Student2 { get; set; }
    }
}
